import { useAuth } from "@/_core/hooks/useAuth";
import { ItemStatusBadge } from "@/components/ItemStatusBadge";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Check, ClipboardCheck, LayoutDashboard, Loader2, PackageSearch, ShieldAlert, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const statuses = ["lost", "found", "resolved", "archived"] as const;

function AdminContent() {
  const { user, loading } = useAuth();
  const [, setLocation] = useLocation();
  const [activeTab, setActiveTab] = useState<"overview" | "items" | "claims">("overview");
  const [itemPage, setItemPage] = useState(1);
  const [notes, setNotes] = useState<Record<number, string>>({});
  const isAdmin = user?.role === "admin";
  const overview = trpc.admin.overview.useQuery(undefined, { enabled: isAdmin });
  const claims = trpc.admin.claims.useQuery(undefined, { enabled: isAdmin });
  const itemsInput = useMemo(() => ({ page: itemPage, pageSize: 12 }), [itemPage]);
  const items = trpc.items.list.useQuery(itemsInput, { enabled: isAdmin });
  const updateStatus = trpc.admin.updateItemStatus.useMutation({ onSuccess: () => { toast.success("Item status updated."); items.refetch(); overview.refetch(); }, onError: error => toast.error(error.message) });
  const reviewClaim = trpc.admin.reviewClaim.useMutation({ onSuccess: () => { toast.success("Claim decision saved and the student notified."); claims.refetch(); overview.refetch(); }, onError: error => toast.error(error.message) });

  if (loading) return <div className="p-8"><div className="h-40 animate-pulse rounded-3xl bg-[#edf2ea]" /></div>;
  if (!isAdmin) return <div className="grid min-h-[65vh] place-items-center p-8 text-center"><div><ShieldAlert className="mx-auto h-9 w-9 text-[#b86244]" /><h1 className="mt-4 text-2xl font-semibold">Administrator access required</h1><p className="mt-2 max-w-sm text-sm leading-6 text-[#718077]">Your account does not have permission to review claims or manage item statuses.</p><Button className="mt-6 rounded-xl" onClick={() => { toast.message("Returning to public reports."); setLocation("/browse"); }}>Return to reports</Button></div></div>;
  const tabClass = (tab: typeof activeTab) => `rounded-xl px-3 py-2 text-sm font-medium transition-colors ${activeTab === tab ? "bg-[#254b42] text-white" : "text-[#5f7469] hover:bg-[#eef3eb]"}`;

  return <div className="mx-auto max-w-7xl"><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#668274]">Control centre</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.045em]">Administrator workspace</h1><p className="mt-2 text-sm text-[#718077]">Review ownership evidence and maintain an accurate campus directory.</p></div><div className="rounded-2xl bg-[#eef4ea] px-4 py-3 text-sm text-[#436b59]"><span className="font-semibold">{overview.data?.pendingClaimCount ?? "—"}</span> claims awaiting review</div></div><div className="mb-7 inline-flex rounded-2xl border border-[#e1e7df] bg-white p-1">{(["overview", "items", "claims"] as const).map(tab => <button key={tab} className={tabClass(tab)} onClick={() => { setActiveTab(tab); toast.message(`Showing ${tab}.`); }}>{tab[0].toUpperCase() + tab.slice(1)}</button>)}</div>
  {activeTab === "overview" ? <>{overview.isError ? <Card className="rounded-2xl border-[#efd7d2] bg-[#fff8f6] p-6 text-center"><p className="font-semibold text-[#963e2d]">Dashboard data could not be loaded</p><Button className="mt-4 rounded-xl" onClick={() => { overview.refetch(); toast.message("Refreshing dashboard data."); }}>Try again</Button></Card> : <><div className="grid gap-4 sm:grid-cols-3"><Card className="rounded-2xl border-[#e1e7df] p-5"><PackageSearch className="h-5 w-5 text-[#4f7d69]" /><p className="mt-4 text-2xl font-semibold">{overview.data?.itemCount ?? "—"}</p><p className="mt-1 text-sm text-[#718077]">Total item reports</p></Card><Card className="rounded-2xl border-[#e1e7df] p-5"><ClipboardCheck className="h-5 w-5 text-[#7a6b32]" /><p className="mt-4 text-2xl font-semibold">{overview.data?.pendingClaimCount ?? "—"}</p><p className="mt-1 text-sm text-[#718077]">Pending claim reviews</p></Card><Card className="rounded-2xl border-[#e1e7df] p-5"><LayoutDashboard className="h-5 w-5 text-[#5873a0]" /><p className="mt-4 text-2xl font-semibold">{overview.data?.claimCount ?? "—"}</p><p className="mt-1 text-sm text-[#718077]">Claims received</p></Card></div><section className="mt-7 rounded-3xl border border-[#e1e7df] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Recent reports</h2><p className="mt-1 text-sm text-[#718077]">Quickly assess the latest reports from the campus community.</p></div><Button variant="outline" className="rounded-xl" onClick={() => { setActiveTab("items"); toast.message("Showing items."); }}>Manage items</Button></div><div className="mt-5 divide-y divide-[#edf0eb]">{overview.isLoading ? <div className="h-32 animate-pulse rounded-xl bg-[#f3f6f1]" /> : overview.data?.recentItems.map(item => <div key={item.id} className="flex flex-col justify-between gap-3 py-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><ItemStatusBadge status={item.status} /><span className="text-xs text-[#738178]">{item.category}</span></div><p className="mt-2 font-medium">{item.title}</p><p className="mt-1 text-xs text-[#78857e]">{item.location} · reported by {item.reporterName || "Student"}</p></div><Button variant="ghost" size="sm" className="rounded-xl" onClick={() => { toast.message("Opening report details."); setLocation(`/items/${item.id}`); }}>Open</Button></div>)}</div></section></>}</> : null}
  {activeTab === "items" ? <section className="rounded-3xl border border-[#e1e7df] bg-white p-5 sm:p-6"><div className="mb-5"><h2 className="font-semibold">All item reports</h2><p className="mt-1 text-sm text-[#718077]">Change a report’s lifecycle status. Only the permitted statuses are available.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-[#edf0eb] text-xs uppercase tracking-[.11em] text-[#7a8880]"><tr><th className="pb-3 pr-4 font-semibold">Item</th><th className="pb-3 pr-4 font-semibold">Report</th><th className="pb-3 pr-4 font-semibold">Current status</th><th className="pb-3 font-semibold">Update</th></tr></thead><tbody>{items.isError ? <tr><td colSpan={4} className="py-12 text-center text-sm text-[#963e2d]">Items could not be loaded. <button className="font-semibold underline" onClick={() => { items.refetch(); toast.message("Refreshing items."); }}>Try again</button></td></tr> : items.isLoading ? <tr><td colSpan={4} className="py-12 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin text-[#608071]" /></td></tr> : items.data?.records.map(item => <tr key={item.id} className="border-b border-[#f0f2ef] last:border-0"><td className="py-4 pr-4"><button className="text-left font-medium hover:text-[#2e6653]" onClick={() => { toast.message("Opening report details."); setLocation(`/items/${item.id}`); }}>{item.title}</button><p className="mt-1 text-xs text-[#78857e]">{item.category} · {item.location}</p></td><td className="py-4 pr-4 capitalize text-[#68766f]">{item.reportType}</td><td className="py-4 pr-4"><ItemStatusBadge status={item.status} /></td><td className="py-4"><select aria-label={`Update ${item.title} status`} defaultValue={item.status} disabled={updateStatus.isPending} onChange={event => updateStatus.mutate({ itemId: item.id, status: event.target.value as typeof statuses[number] })} className="rounded-xl border border-[#dfe6dd] bg-white px-2.5 py-2 text-xs outline-none focus:ring-2 focus:ring-[#527f6d]/30">{statuses.map(status => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div>{items.data ? <div className="mt-5 flex items-center justify-end gap-3"><Button variant="outline" size="sm" className="rounded-xl" disabled={itemPage <= 1} onClick={() => { setItemPage(page => page - 1); toast.message("Showing previous page."); }}>Previous</Button><span className="text-xs text-[#718077]">Page {itemPage} of {items.data.totalPages}</span><Button variant="outline" size="sm" className="rounded-xl" disabled={itemPage >= items.data.totalPages} onClick={() => { setItemPage(page => page + 1); toast.message("Showing next page."); }}>Next</Button></div> : null}</section> : null}
  {activeTab === "claims" ? <section className="rounded-3xl border border-[#e1e7df] bg-white p-5 sm:p-6"><div className="mb-5"><h2 className="font-semibold">Ownership claims</h2><p className="mt-1 text-sm text-[#718077]">Evaluate ownership evidence carefully. A decision alerts the claimant in-app immediately.</p></div><div className="space-y-4">{claims.isError ? <Card className="rounded-2xl border-[#efd7d2] bg-[#fff8f6] p-6 text-center"><p className="font-semibold text-[#963e2d]">Claims could not be loaded</p><Button className="mt-4 rounded-xl" onClick={() => { claims.refetch(); toast.message("Refreshing claims."); }}>Try again</Button></Card> : null}{claims.isLoading ? <div className="h-40 animate-pulse rounded-2xl bg-[#f3f6f1]" /> : null}{!claims.isLoading && !claims.isError && !claims.data?.length ? <div className="rounded-2xl border border-dashed p-10 text-center text-sm text-[#718077]">No ownership claims have been submitted.</div> : null}{claims.data?.map(claim => <Card key={claim.id} className="rounded-2xl border-[#e1e7df] p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{claim.itemTitle}</p><ItemStatusBadge status={claim.claimStatus} /><span className="text-xs text-[#78857e]">Item status: {claim.itemStatus}</span></div><p className="mt-2 text-sm text-[#617169]">Claimant: <span className="font-medium">{claim.claimantName || "Student"}</span>{claim.claimantEmail ? ` · ${claim.claimantEmail}` : ""}</p><p className="mt-4 rounded-xl bg-[#f7faf5] p-3 text-sm leading-6 text-[#5d7166]"><span className="font-semibold text-[#385c4d]">Ownership evidence: </span>{claim.ownershipProof}</p>{claim.adminNote ? <p className="mt-3 text-xs text-[#718077]">Previous note: {claim.adminNote}</p> : null}</div>{claim.claimStatus === "pending" ? <div className="w-full shrink-0 sm:w-72"><Textarea value={notes[claim.id] ?? ""} onChange={event => setNotes(current => ({ ...current, [claim.id]: event.target.value }))} maxLength={800} className="min-h-20 rounded-xl text-xs" placeholder="Optional decision note" /><div className="mt-2 flex gap-2"><Button size="sm" disabled={reviewClaim.isPending} className="flex-1 rounded-xl bg-[#2f714f] hover:bg-[#276043]" onClick={() => reviewClaim.mutate({ claimId: claim.id, decision: "approved", adminNote: notes[claim.id] })}><Check className="mr-1 h-3.5 w-3.5" />Approve</Button><Button size="sm" variant="outline" disabled={reviewClaim.isPending} className="flex-1 rounded-xl border-[#ebc8c2] text-[#a34538] hover:bg-[#fff5f3]" onClick={() => reviewClaim.mutate({ claimId: claim.id, decision: "rejected", adminNote: notes[claim.id] })}><X className="mr-1 h-3.5 w-3.5" />Reject</Button></div></div> : null}</div></Card>)}</div></section> : null}
  </div>;
}

export default function Admin() { return <DashboardLayout><AdminContent /></DashboardLayout>; }
